spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/FullStack
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  # or 'create', 'create-drop', depending on your use case
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.security: trace

jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem
